### ISSUE TITLE
Idea: Permission / ACL and authentication using OAuth or Open ID

### ISSUE THREAD

**Issue by rakucmr** [kohana/auth#24]
What do you think about adding acl and autentification using third-party providers, like in Fuel Framework?

**Comment by shadowhand** [comment]
Auth is deprecated and no new features will be added. Many good libraries to do this already exist.

**Comment by rakucmr** [comment]
Ok, so what will you use?

**Comment by shadowhand** [comment]
For OAuth, [The PHP League](http://thephpleague.com/) makes a high quality server and client. For authentication, you really only need PHP's built in [password_hash](http://php.net/manual/en/function.password-hash.php) function (optional [password_compat](https://github.com/ircmaxell/password_compat) for older versions of PHP). For ACL, I don't like any of the available options and prefer to roll a solution that is part of the application architecture.

**Comment by rjd22** [comment]
https://github.com/cartalyst/sentry is a good one for more complex auth.

**Comment by rakucmr** [comment]
Ok, so will make an warpper over them or use them directrly in our applications?
Also when I was thinking about using Oauth or Open ID my ideea was not to write some classes to do that just to write one Auth driver, like File Auth or ORM Auth that is using HybridAuth - http://hybridauth.sourceforge.net or Opauth - http://opauth.org .
Please excuse my poor English.

**Comment by shadowhand** [comment]
Use them directly in your application. Composer makes it easy. :)
